version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf

build:
  os: "bdsim/alma9-g4.11.2"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install --upgrade --upgrade-strategy only-if-needed furo sphinx>=7.2.2 sphinx-autoapi sphinx-copybutton sphinx-inline-tabs