FROM bdsim/alma9-g4.11.2

RUN git clone git@github.com:bdsim-collaboration/bdsim.git

RUN git checkout v1.7.7

RUN mkdir bdsim_build &&\
    cd bdsim_build &&\
    cmake ../bdsim &&\
    make {{ ncpu }} &&\
    make install &&\
    echo 'source /usr/local/bin/bdsim.sh' >> ~/.bashrc

