name: distribute

on:
  workflow_dispatch:
  release:
    branches:
      - 'master'
  push:
    branches:
      - 'github-distribute'

# readthedocs
# cvmfs
# generate reference data
# mailing list

jobs:
  dockerimage:
    name: Build bdsim docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bdsim
        uses: actions/checkout@v4
        id: checkout

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bdsim/alma9-g4.11.2-v1.7.7

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: .github/docker/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

